/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package naturemarksystems.app

import naturemarksystems.list.LinkedList

import static naturemarksystems.utilities.StringUtils.join
import static naturemarksystems.utilities.StringUtils.split
import static naturemarksystems.app.MessageUtils.getMessage

import org.apache.commons.text.WordUtils

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        String result = join(tokens)
        println(WordUtils.capitalize(result))
    }
}
